### ISSUE TITLE
Failed to call LutimUploader.showSettingsUI()

### ISSUE THREAD

**Issue by na-ji** [Thor77/screencloud-lutim#2]
Hello !

Whenever I want to upload a screenshoot or update the settings, I got a dialog with this error:
```
Failed to call LutimUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 75, in upload
AttributeError: QDesktopServices has no attribute named 'storageLocation'
```
It is probably because I have a newer version of Qt.
How to solve this issue ?

Thanks

**Comment by Thor77** [comment]
Thanks for your report 👍 
Yeah, It's probably caused by a more recent Qt-version.
> How to solve this issue?

I will update the tool asap.

**Comment by Thor77** [comment]
Should be solved now 🎉 
Please confirm

**Comment by na-ji** [comment]
I cannot confirm yet because I have another issue now : 
```
Error in file: ~/.local/share/screencloud/ScreenCloud/plugins/lutim/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: No module named requests
```

**Comment by Thor77** [comment]
Uh, that's probably because of 030190226d77eee51a911d3c20d8e33fa9f08eea (switching from hardcoded requests-source to git-submodule). Thanks for reporting, will fix asap (can't reproduce on my current system, but will try on a clean one)

**Comment by Thor77** [comment]
Should work now (finally) :)

**Comment by Thor77** [comment]
Argh, no, it seems like the submodule is not included in the master-zip. Will try to release the zip manually.

**Comment by Thor77** [comment]
Please try installing the plugin via this url:
```
https://github.com/Thor77/screencloud-lutim/releases/download/v2.0.1/current.zip
```
It does include the requests-package, has the same format as official plugin-zips and should therefore work. If you can confirm, I'll update the link in README.md

**Comment by na-ji** [comment]
Yes it works! Thank you very much @Thor77 for your help. I will now use this plugin on a daily basis :+1:

**Comment by Thor77** [comment]
Great! Glad you like it and have a use for my plugin ✨
